version: "3.8"

services:
  keijiban-php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "80:80"
    volumes:
      - ./../htdocs:/var/www/html

  keijiban-mysql:
    image: mysql
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
      - keijiban:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password

volumes:
  keijiban: