version: "3.8"

services:
  keijiban-php:
    image: php:8.1.7-apache
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "80:80"
    volumes:
      - ./../htdocs:/var/www/html
      - ./../logs/:/var/www/logs

  keijiban-mysql:
    image: mysql
    ports:
      - 37214:37214
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_TCP_PORT=37214
      - MYSQL_DATABASE=test
      - BIND-ADDRESS=0.0.0.0